import '../data.js';
import '../contentExpansion.js';
import '../knowledgeContinuityExpansion.js';
import '../priorityContentExpansion.js';
import '../supplementalContentExpansion.js';
import '../supplementalContentFixes.js';
import '../knowledgeTopology.js';
import '../supplementalTopologyExpansion.js';
import '../mathEssence.js';
import '../conceptAnimations.js';
import '../priorityConceptAnimations.js';
import '../supplementalConceptAnimations.js';
import '../mistakeDiagnosis.js';
import '../supplementalMistakeTags.js';
import '../masteryModel.js';
import '../rewardSystem.js';
import '../questMap.js';
import '../learningSupport.js';
import '../learningEffectEnhancements.js';
import '../answerMatcher.js';
import '../reviewScheduler.js';
import '../reviewQueueModel.js';
import '../adaptivePractice.js';
import '../studentProfiles.js';
import '../appBoot.js';
import '../appState.js';
import '../appSelectors.js';
import '../appDom.js';
import '../app.js';
import '../mathEssenceView.js';
import '../knowledgeTopologyView.js';
import '../learningModes.js';
import '../masteryView.js';
import '../mistakeDiagnosisView.js';
import '../mistakeMap.js';
import '../rewardSystemView.js';
import '../characterStory.js';
import '../questMapView.js';
import '../metroQuestMapView.js';
import '../metroLineEnhancements.js';
import '../stationExperience.js';
import '../routeMission.js';
import '../stationDepthTiers.js';
import '../learningSupportView.js';
import '../productExperience.js';
import '../practiceExperience.js';

const deferEnhancement = window.requestIdleCallback || ((callback) => window.setTimeout(callback, 0));
deferEnhancement(() => {
  import('../conceptAnimationView.js');
  import('../learningReport.js');
  import('../diagnosticEntrance.js');
  import('../stationClearSummary.js');
});
